name: Docker
on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Log into the Docker Registry
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: "Build and push 'latest'"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: "Build and push versioned images"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker build -t $DOCKER_IMAGE:"${GITHUB_REF:11}" .
          docker push $DOCKER_IMAGE:"${GITHUB_REF:11}"

